In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Flatten, Dense, BatchNormalization
from tensorflow.keras.utils import plot_model
from tensorflow.keras.models import Model

###**Dataset link:** https://www.kaggle.com/datasets/ted8080/house-prices-and-images-socal/data

##**Extract the data file**

In [3]:
import zipfile
zip_path='/content/data.zip'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("/content/house_data")

In [ ]:
l=[i for i in os.listdir('/content/house_data/socal2/socal_pics')]
print(len(l))

15330

In [4]:
data=pd.read_csv('/content/house_data/socal2.csv')
df1=data[['image_id', 'price']]
print(df1.shape)
df1.head()

(15474, 2)

   image_id   price
0         0  201900
1         1  228500
2         2  273950
3         3  350000
4         4  385100

##**Create label**

In [5]:
import os
import cv2
image=[]
label=[]
path='/content/house_data/socal2/socal_pics'
for img in os.listdir(path):
  label.append(int(img.split('.')[0]))
  image.append(img)
print((image))
print((label))

['1942.jpg', '1934.jpg', '2191.jpg', '5362.jpg', '11758.jpg', '13414.jpg', '2000.jpg', '13652.jpg', '1977.jpg', '9562.jpg', '14592.jpg', '12991.jpg', '5586.jpg', '92.jpg', '9575.jpg', '13422.jpg', '13348.jpg', '6487.jpg', '2464.jpg', '8764.jpg', '11391.jpg', '5523.jpg', '2458.jpg', '8441.jpg', '1350.jpg', '3787.jpg', '11051.jpg', '1479.jpg', '5941.jpg', '14876.jpg', '13614.jpg', '583.jpg', '475.jpg', '13201.jpg', '1573.jpg', '8095.jpg', '11865.jpg', '5335.jpg', '6242.jpg', '727.jpg', '14956.jpg', '11764.jpg', '9236.jpg', '6039.jpg', '4691.jpg', '11371.jpg', '13000.jpg', '274.jpg', '3933.jpg', '8695.jpg', '13850.jpg', '9121.jpg', '8810.jpg', '15044.jpg', '8847.jpg', '13394.jpg', '8513.jpg', '4807.jpg', '12355.jpg', '14928.jpg', '15383.jpg', '9877.jpg', '14721.jpg', '10675.jpg', '8754.jpg', '5495.jpg', '14954.jpg', '4763.jpg', '3081.jpg', '1960.jpg', '13831.jpg', '3096.jpg', '14405.jpg', '12097.jpg', '6761.jpg', '6754.jpg', '10186.jpg', '1871.jpg', '1849.jpg', '11690.jpg', '4368.jpg', '2205.jpg', '11891.jpg', '11788.jpg', '5049.jpg', '2693.jpg', '13479.jpg', '2211.jpg', '14736.jpg', '6049.jpg', '12746.jpg', '9672.jpg', '10019.jpg', '5147.jpg', '9847.jpg', '13714.jpg', '14215.jpg', '6424.jpg', '7150.jpg', '12557.jpg', '12928.jpg', '8697.jpg', '4915.jpg', '2975.jpg', '9005.jpg', '4934.jpg', '10316.jpg', '15244.jpg', '12737.jpg', '477.jpg', '14371.jpg', '9103.jpg', '11612.jpg', '13269.jpg', '10564.jpg', '11365.jpg', '8114.jpg', '14785.jpg', '8193.jpg', '7679.jpg', '8178.jpg', '15371.jpg', '4643.jpg', '4289.jpg', '3307.jpg', '11337.jpg', '7195.jpg', '5284.jpg', '14059.jpg', '2187.jpg', '5078.jpg', '5069.jpg', '1746.jpg', '9481.jpg', '4362.jpg', '8399.jpg', '10503.jpg', '10112.jpg', '9283.jpg', '12005.jpg', '12791.jpg', '7571.jpg', '3963.jpg', '10421.jpg', '13161.jpg', '9636.jpg', '6729.jpg', '5678.jpg', '14582.jpg', '8543.jpg', '12058.jpg', '14660.jpg', '4971.jpg', '229.jpg', '5215.jpg', '4013.jpg', '8643.jpg', '13243.jpg', '6299.jpg', '14473.jpg', '6609.jpg', '14492.jpg', '3531.jpg', '6295.jpg', '6303.jpg', '8221.jpg', '3535.jpg', '8795.jpg', '2604.jpg', '11368.jpg', '10679.jpg', '14821.jpg', '10065.jpg', '554.jpg', '5211.jpg', '2332.jpg', '13084.jpg', '2938.jpg', '5927.jpg', '8174.jpg', '671.jpg', '1880.jpg', '3629.jpg', '3097.jpg', '9410.jpg', '12550.jpg', '12572.jpg', '8802.jpg', '13602.jpg', '10881.jpg', '7116.jpg', '13562.jpg', '15188.jpg', '351.jpg', '8562.jpg', '9407.jpg', '9036.jpg', '10544.jpg', '6716.jpg', '6851.jpg', '5357.jpg', '14255.jpg', '3109.jpg', '12221.jpg', '13788.jpg', '6093.jpg', '6520.jpg', '8800.jpg', '14218.jpg', '7019.jpg', '6561.jpg', '1990.jpg', '6655.jpg', '9314.jpg', '9142.jpg', '6541.jpg', '41.jpg', '15327.jpg', '444.jpg', '11050.jpg', '9030.jpg', '13407.jpg', '14927.jpg', '4468.jpg', '8317.jpg', '11364.jpg', '13275.jpg', '15434.jpg', '13830.jpg', '2936.jpg', '4159.jpg', '3942.jpg', '6783.jpg', '5124.jpg', '7898.jpg', '1882.jpg', '14140.jpg', '13981.jpg', '8930.jpg', '13185.jpg', '4980.jpg', '3841.jpg', '1565.jpg', '13179.jpg', '12912.jpg', '4882.jpg', '6172.jpg', '11680.jpg', '8365.jpg', '10189.jpg', '3570.jpg', '13645.jpg', '12272.jpg', '3121.jpg', '9104.jpg', '7470.jpg', '2883.jpg', '517.jpg', '11065.jpg', '13837.jpg', '1805.jpg', '5141.jpg', '6572.jpg', '8670.jpg', '14852.jpg', '15415.jpg', '614.jpg', '6842.jpg', '13902.jpg', '439.jpg', '7076.jpg', '14360.jpg', '14480.jpg', '872.jpg', '12537.jpg', '15348.jpg', '9067.jpg', '9811.jpg', '12702.jpg', '2374.jpg', '15251.jpg', '4416.jpg', '11511.jpg', '4177.jpg', '12699.jpg', '5347.jpg', '10891.jpg', '12425.jpg', '11580.jpg', '4451.jpg', '668.jpg', '3461.jpg', '1230.jpg', '5960.jpg', '13169.jpg', '169.jpg', '13801.jpg', '14504.jpg', '13783.jpg', '12382.jpg', '9818.jpg', '10797.jpg', '7523.jpg', '5000.jpg', '14382.jpg', '1915.jpg', '12876.jpg', '2538.jpg', '2035.jpg', '11844.jpg', '589.jpg', '10328.jpg', '168.jpg', '4901.jpg', '14759.jpg', '12930.jpg', '9612.jpg', '4373.jpg', '1399.jpg', '3514.jpg', '4344.jpg', '1589.jpg', '14874.jpg', '6917.jpg', '51.jpg', '9838.jpg', '508.jpg', '14709.jpg', '10746.jpg', '4129.jpg', '2562.jpg', '14024.jpg', '12498.jpg', '660.jpg', '13134.jpg', '253.jpg', '13220.jpg', '1884.jpg', '13973.jpg', '4827.jpg', '12819.jpg', '4068.jpg', '11670.jpg', '2610.jpg', '734.jpg', '6246.jpg', '9400.jpg', '12993.jpg', '6778.jpg', '6676.jpg', '10263.jpg', '1180.jpg', '3760.jpg', '9732.jpg', '10914.jpg', '9853.jpg', '9101.jpg', '6925.jpg', '2046.jpg', '10750.jpg', '5533.jpg', '12452.jpg', '13833.jpg', '14669.jpg', '10485.jpg', '7488.jpg', '7336.jpg', '4205.jpg', '1164.jpg', '14818.jpg', '811.jpg', '10767.jpg', '1631.jpg', '12917.jpg', '10995.jpg', '234.jpg', '9588.jpg', '2289.jpg', '9098.jpg', '7422.jpg', '7381.jpg', '13430.jpg', '3564.jpg', '10932.jpg', '5706.jpg', '5033.jpg', '11303.jpg', '5844.jpg', '5420.jpg', '2343.jpg', '5903.jpg', '14982.jpg', '1648.jpg', '10308.jpg', '9960.jpg', '9553.jpg', '3449.jpg', '4047.jpg', '1457.jpg', '2088.jpg', '12178.jpg', '12752.jpg', '10872.jpg', '2768.jpg', '8604.jpg', '11755.jpg', '1591.jpg', '14897.jpg', '11184.jpg', '5321.jpg', '12054.jpg', '9330.jpg', '11769.jpg', '3847.jpg', '7393.jpg', '14972.jpg', '2525.jpg', '8616.jpg', '829.jpg', '11686.jpg', '943.jpg', '10416.jpg', '7277.jpg', '14139.jpg', '11551.jpg', '1484.jpg', '10229.jpg', '1275.jpg', '402.jpg', '4100.jpg', '6437.jpg', '95.jpg', '3631.jpg', '13031.jpg', '7752.jpg', '7806.jpg', '6807.jpg', '3842.jpg', '3382.jpg', '14846.jpg', '802.jpg', '11403.jpg', '15390.jpg', '7016.jpg', '2149.jpg', '2778.jpg', '7933.jpg', '441.jpg', '14132.jpg', '7156.jpg', '10424.jpg', '3624.jpg', '5736.jpg', '14506.jpg', '11976.jpg', '712.jpg', '8008.jpg', '4914.jpg', '15189.jpg', '10107.jpg', '1719.jpg', '6678.jpg', '3966.jpg', '13522.jpg', '3951.jpg', '4710.jpg', '9163.jpg', '388.jpg', '8934.jpg', '3808.jpg', '12624.jpg', '11904.jpg', '11789.jpg', '11159.jpg', '7113.jpg', '3400.jpg', '12328.jpg', '15212.jpg', '9460.jpg', '14498.jpg', '4904.jpg', '13373.jpg', '9915.jpg', '3193.jpg', '11126.jpg', '10605.jpg', '543.jpg', '8840.jpg', '7552.jpg', '13351.jpg', '6107.jpg', '14871.jpg', '2615.jpg', '11284.jpg', '7394.jpg', '776.jpg', '8698.jpg', '2030.jpg', '14849.jpg', '10713.jpg', '7315.jpg', '8905.jpg', '5924.jpg', '14947.jpg', '4960.jpg', '4869.jpg', '1900.jpg', '2916.jpg', '8140.jpg', '1929.jpg', '9208.jpg', '15083.jpg', '14440.jpg', '6226.jpg', '14073.jpg', '4043.jpg', '611.jpg', '5568.jpg', '1958.jpg', '10243.jpg', '13946.jpg', '15410.jpg', '14667.jpg', '6680.jpg', '3892.jpg', '6530.jpg', '6324.jpg', '6578.jpg', '6244.jpg', '8370.jpg', '1865.jpg', '10556.jpg', '4219.jpg', '4818.jpg', '10530.jpg', '1266.jpg', '1395.jpg', '7369.jpg', '13079.jpg', '263.jpg', '12669.jpg', '6699.jpg', '6162.jpg', '5455.jpg', '1641.jpg', '1344.jpg', '13107.jpg', '2239.jpg', '3586.jpg', '1106.jpg', '8169.jpg', '8355.jpg', '13027.jpg', '9512.jpg', '13358.jpg', '13988.jpg', '3172.jpg', '13186.jpg', '12454.jpg', '13397.jpg', '6606.jpg', '7680.jpg', '1131.jpg', '2526.jpg', '9153.jpg', '13240.jpg', '7332.jpg', '9190.jpg', '9360.jpg', '2092.jpg', '6875.jpg', '8577.jpg', '7071.jpg', '3155.jpg', '6066.jpg', '437.jpg', '5264.jpg', '9524.jpg', '1742.jpg', '5510.jpg', '356.jpg', '11239.jpg', '11165.jpg', '13677.jpg', '252.jpg', '12524.jpg', '11430.jpg', '11324.jpg', '15252.jpg', '15468.jpg', '13400.jpg', '8367.jpg', '12060.jpg', '15292.jpg', '4761.jpg', '10446.jpg', '6723.jpg', '15228.jpg', '6141.jpg', '13054.jpg', '5644.jpg', '12196.jpg', '11122.jpg', '2352.jpg', '9293.jpg', '13446.jpg', '5481.jpg', '15004.jpg', '9654.jpg', '13387.jpg', '10477.jpg', '3572.jpg', '10450.jpg', '8320.jpg', '10500.jpg', '6188.jpg', '13881.jpg', '3271.jpg', '8444.jpg', '14070.jpg', '830.jpg', '2639.jpg', '14118.jpg', '13343.jpg', '6482.jpg', '6423.jpg', '10836.jpg', '11131.jpg', '12350.jpg', '2488.jpg', '708.jpg', '13855.jpg', '1352.jpg', '12347.jpg', '4739.jpg', '11104.jpg', '4772.jpg', '6355.jpg', '15154.jpg', '13347.jpg', '9832.jpg', '6618.jpg', '7115.jpg', '1408.jpg', '7991.jpg', '11767.jpg', '11409.jpg', '2658.jpg', '13710.jpg', '1623.jpg', '12525.jpg', '6921.jpg', '2185.jpg', '9424.jpg', '13725.jpg', '4806.jpg', '4239.jpg', '5613.jpg', '5360.jpg', '3248.jpg', '10805.jpg', '8455.jpg', '13181.jpg', '14783.jpg', '9385.jpg', '4247.jpg', '14909.jpg', '7531.jpg', '553.jpg', '7641.jpg', '3752.jpg', '6544.jpg', '6564.jpg', '243.jpg', '11435.jpg', '11268.jpg', '7901.jpg', '13335.jpg', '11287.jpg', '6467.jpg', '12604.jpg', '5207.jpg', '7693.jpg', '6282.jpg', '2224.jpg', '6978.jpg', '14864.jpg', '3301.jpg', '11929.jpg', '3751.jpg', '7344.jpg', '12275.jpg', '9937.jpg', '7198.jpg', '14363.jpg', '7783.jpg', '8744.jpg', '12281.jpg', '2414.jpg', '2930.jpg', '8043.jpg', '5376.jpg', '13029.jpg', '11111.jpg', '10999.jpg', '10028.jpg', '12783.jpg', '3472.jpg', '2971.jpg', '8217.jpg', '1563.jpg', '4974.jpg', '5595.jpg', '13005.jpg', '1401.jpg', '13257.jpg', '3641.jpg', '2133.jpg', '7351.jpg', '9890.jpg', '14341.jpg', '12931.jpg', '8557.jpg', '11623.jpg', '1948.jpg', '14110.jpg', '8883.jpg', '810.jpg', '326.jpg', '2918.jpg', '9646.jpg', '4341.jpg', '11561.jpg', '14803.jpg', '8977.jpg', '9113.jpg', '9531.jpg', '7554.jpg', '10017.jpg', '8651.jpg', '11964.jpg', '7703.jpg', '3749.jpg', '7961.jpg', '7281.jpg', '4245.jpg', '12962.jpg', '5576.jpg', '11186.jpg', '5530.jpg', '8157.jpg', '8625.jpg', '4844.jpg', '1720.jpg', '1179.jpg', '14317.jpg', '3280.jpg', '12184.jpg', '9871.jpg', '3481.jpg', '14108.jpg', '13254.jpg', '8881.jpg', '4352.jpg', '10771.jpg', '12442.jpg', '5521.jpg', '2803.jpg', '5918.jpg', '6109.jpg', '12619.jpg', '7980.jpg', '14798.jpg', '8434.jpg', '7955.jpg', '13992.jpg', '11645.jpg', '4208.jpg', '4376.jpg', '4147.jpg', '7622.jpg', '12002.jpg', '12612.jpg', '1928.jpg', '35.jpg', '14806.jpg', '813.jpg', '9211.jpg', '12797.jpg', '5840.jpg', '1640.jpg', '1876.jpg', '6359.jpg', '15384.jpg', '11355.jpg', '10829.jpg', '2081.jpg', '2753.jpg', '13842.jpg', '9287.jpg', '11048.jpg', '9129.jpg', '13872.jpg', '1255.jpg', '10058.jpg', '6950.jpg', '5319.jpg', '7262.jpg', '9702.jpg', '8965.jpg', '5604.jpg', '8395.jpg', '4575.jpg', '4793.jpg', '5692.jpg', '15349.jpg', '483.jpg', '1862.jpg', '7101.jpg', '13409.jpg', '2605.jpg', '7812.jpg', '2980.jpg', '11298.jpg', '1380.jpg', '4032.jpg', '13978.jpg', '5320.jpg', '10528.jpg', '3818.jpg', '13791.jpg', '14696.jpg', '10732.jpg', '12732.jpg', '3215.jpg', '11828.jpg', '386.jpg', '3596.jpg', '6069.jpg', '10601.jpg', '15039.jpg', '12426.jpg', '10067.jpg', '2225.jpg', '2102.jpg', '7427.jpg', '15344.jpg', '538.jpg', '6082.jpg', '9748.jpg', '11090.jpg', '6010.jpg', '11557.jpg', '5085.jpg', '3625.jpg', '2068.jpg', '5497.jpg', '2062.jpg', '9693.jpg', '10203.jpg', '13802.jpg', '1840.jpg', '4961.jpg', '9952.jpg', '1489.jpg', '6743.jpg', '499.jpg', '11700.jpg', '6668.jpg', '4986.jpg', '13143.jpg', '7970.jpg', '6614.jpg', '14271.jpg', '526.jpg', '14260.jpg', '4415.jpg', '10265.jpg', '14815.jpg', '4707.jpg', '4226.jpg', '6416.jpg', '7789.jpg', '12299.jpg', '8864.jpg', '1304.jpg', '2202.jpg', '10082.jpg', '2896.jpg', '3795.jpg', '2463.jpg', '12939.jpg', '1690.jpg', '13377.jpg', '965.jpg', '6554.jpg', '6828.jpg', '6526.jpg', '12683.jpg', '425.jpg', '13388.jpg', '2059.jpg', '3337.jpg', '7971.jpg', '13590.jpg', '1762.jpg', '12546.jpg', '409.jpg', '4809.jpg', '15018.jpg', '8629.jpg', '7791.jpg', '78.jpg', '10061.jpg', '33.jpg', '14021.jpg', '1511.jpg', '3316.jpg', '11638.jpg', '14310.jpg', '12533.jpg', '1964.jpg', '12990.jpg', '10162.jpg', '8308.jpg', '9322.jpg', '14160.jpg', '11312.jpg', '4312.jpg', '7138.jpg', '9995.jpg', '5114.jpg', '6452.jpg', '551.jpg', '11444.jpg', '8523.jpg', '5660.jpg', '5796.jpg', '11512.jpg', '261.jpg', '7337.jpg', '9677.jpg', '6553.jpg', '12739.jpg', '6170.jpg', '4336.jpg', '6713.jpg', '3137.jpg', '1868.jpg', '4465.jpg', '135.jpg', '1406.jpg', '6060.jpg', '8090.jpg', '7340.jpg', '991.jpg', '7473.jpg', '14970.jpg', '9254.jpg', '9300.jpg', '9515.jpg', '6597.jpg', '7048.jpg', '3615.jpg', '740.jpg', '7061.jpg', '3706.jpg', '12061.jpg', '14936.jpg', '1129.jpg', '8558.jpg', '5722.jpg', '5128.jpg', '7820.jpg', '8394.jpg', '12402.jpg', '9146.jpg', '7129.jpg', '12137.jpg', '14400.jpg', '10190.jpg', '26.jpg', '9084.jpg', '12362.jpg', '14780.jpg', '6388.jpg', '3652.jpg', '11517.jpg', '10895.jpg', '8472.jpg', '7597.jpg', '14682.jpg', '11923.jpg', '120.jpg', '7973.jpg', '12211.jpg', '8031.jpg', '13540.jpg', '14544.jpg', '2815.jpg', '1947.jpg', '11437.jpg', '8927.jpg', '15432.jpg', '6957.jpg', '10708.jpg', '10756.jpg', '8121.jpg', '12670.jpg', '1883.jpg', '13671.jpg', '6267.jpg', '1141.jpg', '11157.jpg', '1700.jpg', '497.jpg', '3594.jpg', '10099.jpg', '9686.jpg', '2271.jpg', '14433.jpg', '11971.jpg', '272.jpg', '154.jpg', '15418.jpg', '11377.jpg', '2757.jpg', '3945.jpg', '11600.jpg', '5596.jpg', '4060.jpg', '6011.jpg', '4801.jpg', '7166.jpg', '999.jpg', '638.jpg', '4485.jpg', '4541.jpg', '876.jpg', '11103.jpg', '7197.jpg', '3511.jpg', '7235.jpg', '4080.jpg', '1600.jpg', '6627.jpg', '3256.jpg', '8554.jpg', '4116.jpg', '5950.jpg', '7975.jpg', '2142.jpg', '8428.jpg', '4561.jpg', '14867.jpg', '9873.jpg', '623.jpg', '9282.jpg', '4265.jpg', '11246.jpg', '3401.jpg', '2592.jpg', '4690.jpg', '6906.jpg', '14966.jpg', '7687.jpg', '9865.jpg', '8703.jpg', '206.jpg', '1176.jpg', '5955.jpg', '8280.jpg', '5275.jpg', '5064.jpg', '11362.jpg', '10487.jpg', '2991.jpg', '12122.jpg', '8797.jpg', '4982.jpg', '1308.jpg', '14127.jpg', '4173.jpg', '10913.jpg', '1783.jpg', '4149.jpg', '9139.jpg', '2851.jpg', '946.jpg', '8356.jpg', '8544.jpg', '1627.jpg', '13482.jpg', '6371.jpg', '6366.jpg', '3579.jpg', '10288.jpg', '10733.jpg', '6814.jpg', '13574.jpg', '14004.jpg', '1788.jpg', '2541.jpg', '8711.jpg', '3454.jpg', '4716.jpg', '11727.jpg', '1796.jpg', '9395.jpg', '3415.jpg', '7338.jpg', '4725.jpg', '8201.jpg', '2012.jpg', '4774.jpg', '6283.jpg', '2964.jpg', '5545.jpg', '12569.jpg', '3890.jpg', '4111.jpg', '12731.jpg', '8359.jpg', '2164.jpg', '1653.jpg', '13168.jpg', '8377.jpg', '13722.jpg', '11342.jpg', '9279.jpg', '2531.jpg', '13091.jpg', '12688.jpg', '3976.jpg', '1472.jpg', '6408.jpg', '9473.jpg', '4598.jpg', '8293.jpg', '5723.jpg', '160.jpg', '12466.jpg', '10277.jpg', '11648.jpg', '6438.jpg', '1224.jpg', '12694.jpg', '7214.jpg', '5964.jpg', '11473.jpg', '4609.jpg', '12202.jpg', '3425.jpg', '11900.jpg', '863.jpg', '3524.jpg', '7144.jpg', '9700.jpg', '14209.jpg', '14656.jpg', '14470.jpg', '11937.jpg', '12304.jpg', '3116.jpg', '9179.jpg', '14239.jpg', '8087.jpg', '13103.jpg', '1325.jpg', '8749.jpg', '1614.jpg', '684.jpg', '14646.jpg', '7749.jpg', '14214.jpg', '4902.jpg', '5279.jpg', '5228.jpg', '1775.jpg', '3311.jpg', '2717.jpg', '331.jpg', '15261.jpg', '6775.jpg', '14729.jpg', '12139.jpg', '10322.jpg', '13774.jpg', '7271.jpg', '988.jpg', '13977.jpg', '9658.jpg', '5359.jpg', '6018.jpg', '7767.jpg', '3313.jpg', '5623.jpg', '11884.jpg', '4174.jpg', '15255.jpg', '4503.jpg', '113.jpg', '1798.jpg', '11491.jpg', '5780.jpg', '3552.jpg', '15460.jpg', '4870.jpg', '12399.jpg', '6762.jpg', '8360.jpg', '12336.jpg', '13058.jpg', '3474.jpg', '6414.jpg', '6449.jpg', '13231.jpg', '5683.jpg', '5434.jpg', '7506.jpg', '1200.jpg', '6252.jpg', '2748.jpg', '3973.jpg', '3862.jpg', '2079.jpg', '13584.jpg', '14870.jpg', '12381.jpg', '8962.jpg', '12968.jpg', '586.jpg', '7855.jpg', '14283.jpg', '6027.jpg', '3439.jpg', '10920.jpg', '15359.jpg', '7889.jpg', '5260.jpg', '8755.jpg', '266.jpg', '6722.jpg', '13843.jpg', '8556.jpg', '14714.jpg', '1360.jpg', '7868.jpg', '3286.jpg', '4527.jpg', '10691.jpg', '1552.jpg', '3365.jpg', '5785.jpg', '156.jpg', '7941.jpg', '8690.jpg', '4449.jpg', '9598.jpg', '10005.jpg', '13164.jpg', '2825.jpg', '14111.jpg', '594.jpg', '13313.jpg', '15170.jpg', '12185.jpg', '5157.jpg', '5167.jpg', '133.jpg', '12351.jpg', '12329.jpg', '7480.jpg', '1426.jpg', '4839.jpg', '6033.jpg', '4674.jpg', '2584.jpg', '13332.jpg', '8350.jpg', '334.jpg', '10336.jpg', '11519.jpg', '6316.jpg', '6298.jpg', '12044.jpg', '12463.jpg', '4109.jpg', '766.jpg', '13193.jpg', '5721.jpg', '1326.jpg', '12528.jpg', '15373.jpg', '6081.jpg', '4860.jpg', '9568.jpg', '13363.jpg', '14483.jpg', '3079.jpg', '9783.jpg', '13961.jpg', '15103.jpg', '14146.jpg', '11955.jpg', '13814.jpg', '13859.jpg', '2478.jpg', '3177.jpg', '14697.jpg', '14008.jpg', '9334.jpg', '13668.jpg', '751.jpg', '4498.jpg', '13419.jpg', '6971.jpg', '9920.jpg', '13616.jpg', '15158.jpg', '4962.jpg', '7074.jpg', '10306.jpg', '4011.jpg', '3397.jpg', '4447.jpg', '9120.jpg', '2462.jpg', '777.jpg', '1925.jpg', '14242.jpg', '4891.jpg', '6718.jpg', '4414.jpg', '5238.jpg', '14250.jpg', '8154.jpg', '11627.jpg', '7802.jpg', '13147.jpg', '804.jpg', '4394.jpg', '9671.jpg', '2075.jpg', '13362.jpg', '4950.jpg', '6854.jpg', '1476.jpg', '13993.jpg', '12305.jpg', '7827.jpg', '884.jpg', '6317.jpg', '6768.jpg', '8127.jpg', '2229.jpg', '14976.jpg', '10794.jpg', '11933.jpg', '3005.jpg', '9570.jpg', '7721.jpg', '8646.jpg', '10013.jpg', '800.jpg', '8134.jpg', '7781.jpg', '8715.jpg', '7498.jpg', '11756.jpg', '2698.jpg', '12995.jpg', '14946.jpg', '6504.jpg', '3111.jpg', '10518.jpg', '13663.jpg', '2992.jpg', '5209.jpg', '6834.jpg', '5789.jpg', '5690.jpg', '13057.jpg', '10226.jpg', '56.jpg', '1741.jpg', '8752.jpg', '8793.jpg', '5295.jpg', '7520.jpg', '4443.jpg', '6150.jpg', '8023.jpg', '14545.jpg', '12966.jpg', '9214.jpg', '12377.jpg', '7817.jpg', '3047.jpg', '10091.jpg', '242.jpg', '9402.jpg', '12841.jpg', '14304.jpg', '5403.jpg', '8473.jpg', '15110.jpg', '3558.jpg', '11944.jpg', '6975.jpg', '3160.jpg', '12561.jpg', '10761.jpg', '11160.jpg', '3923.jpg', '11327.jpg', '12494.jpg', '11763.jpg', '11593.jpg', '3009.jpg', '5165.jpg', '5606.jpg', '3700.jpg', '11509.jpg', '1553.jpg', '8821.jpg', '8209.jpg', '6519.jpg', '14258.jpg', '5699.jpg', '7930.jpg', '6770.jpg', '3940.jpg', '6352.jpg', '14836.jpg', '8097.jpg', '14747.jpg', '14424.jpg', '6402.jpg', '228.jpg', '8102.jpg', '13475.jpg', '8100.jpg', '13069.jpg', '9276.jpg', '3240.jpg', '1403.jpg', '4984.jpg', '11088.jpg', '13556.jpg', '6505.jpg', '10417.jpg', '4721.jpg', '6757.jpg', '8050.jpg', '13518.jpg', '7109.jpg', '1945.jpg', '13950.jpg', '9148.jpg', '10411.jpg', '5902.jpg', '2998.jpg', '12655.jpg', '5560.jpg', '5102.jpg', '3229.jpg', '3633.jpg', '7087.jpg', '6268.jpg', '12084.jpg', '10092.jpg', '8576.jpg', '4271.jpg', '5843.jpg', '992.jpg', '283.jpg', '8968.jpg', '7633.jpg', '8931.jpg', '1474.jpg', '5366.jpg', '221.jpg', '14046.jpg', '13238.jpg', '4417.jpg', '3372.jpg', '4168.jpg', '2535.jpg', '7701.jpg', '1550.jpg', '5235.jpg', '9106.jpg', '6439.jpg', '879.jpg', '54.jpg', '5373.jpg', '9362.jpg', '8619.jpg', '2401.jpg', '1522.jpg', '7105.jpg', '10801.jpg', '13597.jpg', '1688.jpg', '8824.jpg', '12974.jpg', '14853.jpg', '7596.jpg', '2744.jpg', '7853.jpg', '9107.jpg', '1353.jpg', '5398.jpg', '1886.jpg', '1562.jpg', '14116.jpg', '1113.jpg', '5259.jpg', '12478.jpg', '11852.jpg', '6856.jpg', '10818.jpg', '2020.jpg', '3264.jpg', '12667.jpg', '7148.jpg', '5642.jpg', '5907.jpg', '5754.jpg', '10596.jpg', '7829.jpg', '14948.jpg', '3380.jpg', '9015.jpg', '11584.jpg', '413.jpg', '14362.jpg', '6002.jpg', '12133.jpg', '8185.jpg', '1181.jpg', '15449.jpg', '10093.jpg', '3124.jpg', '1847.jpg', '10613.jpg', '9889.jpg', '11310.jpg', '9264.jpg', '5698.jpg', '9678.jpg', '1864.jpg', '6644.jpg', '10330.jpg', '3580.jpg', '3255.jpg', '4351.jpg', '5353.jpg', '8171.jpg', '12360.jpg', '5870.jpg', '9564.jpg', '2711.jpg', '544.jpg', '12376.jpg', '12057.jpg', '2212.jpg', '13033.jpg', '7712.jpg', '1542.jpg', '11738.jpg', '11189.jpg', '11928.jpg', '14776.jpg', '13063.jpg', '6146.jpg', '739.jpg', '11336.jpg', '13923.jpg', '13893.jpg', '7574.jpg', '3417.jpg', '6670.jpg', '183.jpg', '8692.jpg', '9939.jpg', '315.jpg', '7623.jpg', '7918.jpg', '7225.jpg', '5121.jpg', '112.jpg', '10570.jpg', '14501.jpg', '14375.jpg', '2257.jpg', '15135.jpg', '2599.jpg', '13486.jpg', '3200.jpg', '9794.jpg', '15340.jpg', '6626.jpg', '10422.jpg', '1267.jpg', '13693.jpg', '14767.jpg', '9696.jpg', '9220.jpg', '3273.jpg', '12038.jpg', '715.jpg', '5928.jpg', '14934.jpg', '3139.jpg', '13760.jpg', '5835.jpg', '3168.jpg', '2623.jpg', '3069.jpg', '2572.jpg', '8855.jpg', '11454.jpg', '5794.jpg', '5104.jpg', '13724.jpg', '2724.jpg', '11605.jpg', '

In [6]:
df2=df1[df1['image_id'].isin(label)]
df2=df2.reset_index(drop=True)
df2.head()

   image_id   price
0         2  273950
1         3  350000
2         4  385100
3         5  350000
4         6  415000

In [7]:
df3=pd.DataFrame({'img_id':label, 'Image':image})
df3=df3.sort_values(by='img_id')
df3=df3.reset_index(drop=True)
df3.head()

   img_id  Image
0       2  2.jpg
1       3  3.jpg
2       4  4.jpg
3       5  5.jpg
4       6  6.jpg

##**Finale Data**

In [8]:
df=df3
df['price']=df2['price']
print(df.shape)
df.head(5)

(15330, 3)

   img_id  Image   price
0       2  2.jpg  273950
1       3  3.jpg  350000
2       4  4.jpg  385100
3       5  5.jpg  350000
4       6  6.jpg  415000

In [16]:
df['price']=np.log(df['price'])
df

       img_id      Image     price
0           2      2.jpg  2.527383
1           3      3.jpg  2.546761
2           4      4.jpg  2.554220
3           5      5.jpg  2.546761
4           6      6.jpg  2.560017
...       ...        ...       ...
15325   15469  15469.jpg  2.621996
15326   15470  15470.jpg  2.622065
15327   15471  15471.jpg  2.619738
15328   15472  15472.jpg  2.625574
15329   15473  15473.jpg  2.623958

[15330 rows x 3 columns]

##**Train Test Split**

In [17]:
train_df=df.sample(frac=1, random_state=0).iloc[0:200]
test_df=df.sample(frac=1, random_state=0).iloc[201:300]

In [18]:
print('shape of train_df', train_df.shape)
print('shape of test_df', test_df.shape)

shape of train_df (200, 3)
shape of test_df (99, 3)

##**Data Augumentation**

In [19]:
train_generator=ImageDataGenerator(
    rescale=1./255 ,
    rotation_range=30 ,
    zoom_range=0.2 ,
    shear_range=0.2 ,
    width_shift_range=0.2 ,
    height_shift_range=0.2 ,
    horizontal_flip=True
)

val_generator=ImageDataGenerator(
    rescale=1./255 ,
    rotation_range=30,
    shear_range=0.2,
    zoom_range=0.2,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True
)


train_ds=train_generator.flow_from_dataframe(
    train_df,
    directory=path ,
    x_col='Image',
    y_col=['price'] ,
    target_size=(200,200) ,
    class_mode='raw'
)

val_ds=val_generator.flow_from_dataframe(
    test_df ,
    directory=path,
    x_col='Image' ,
    y_col=['price'] ,
    target_size=(200,200),
    class_mode='raw'

)

Found 200 validated image filenames.
Found 99 validated image filenames.

In [20]:
for images, labels in train_ds.take(1):
  print(images, labels)

AttributeError: 'DataFrameIterator' object has no attribute 'take'

In [21]:
print(type(train_ds))
print(type(val_ds))

<class 'keras.src.legacy.preprocessing.image.DataFrameIterator'>
<class 'keras.src.legacy.preprocessing.image.DataFrameIterator'>

##**Train the Model**

In [22]:
resnet=ResNet50(include_top=False, input_shape=(200,200,3))

resnet.trainable=False

res_output=resnet.output

flat=Flatten()(res_output)

batch1=BatchNormalization()(flat)

dense1=Dense(128, activation='relu')(batch1)

batch2=BatchNormalization()(dense1)

dense2=Dense(128, activation='relu')(batch2)

batch3=BatchNormalization()(dense2)

dense3=Dense(64, activation='relu')(batch3)

batch4=BatchNormalization()(dense3)

output1=Dense(1, activation='linear', name='price')(batch4)

model=Model(inputs=resnet.input, outputs=output1)

##**Compile and Evaluate the mode**

In [23]:
model.compile(optimizer='adam', loss='mae', metrics=['mae'])

model.fit(train_ds, epochs=20, validation_data=val_ds)

Epoch 1/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 76s 9s/step - loss: 2.5878 - mae: 2.5878 - val_loss: 0.6234 - val_mae: 0.6234
Epoch 2/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 56s 8s/step - loss: 2.4848 - mae: 2.4848 - val_loss: 1.2713 - val_mae: 1.2713
Epoch 3/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 55s 8s/step - loss: 2.4021 - mae: 2.4021 - val_loss: 1.5498 - val_mae: 1.5498
Epoch 4/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 57s 9s/step - loss: 2.3200 - mae: 2.3200 - val_loss: 1.7449 - val_mae: 1.7449
Epoch 5/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 55s 9s/step - loss: 2.2346 - mae: 2.2346 - val_loss: 2.6913 - val_mae: 2.6913
Epoch 6/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 55s 8s/step - loss: 2.1490 - mae: 2.1490 - val_loss: 2.6879 - val_mae: 2.6879
Epoch 7/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 55s 8s/step - loss: 2.0626 - mae: 2.0626 - val_loss: 1.1787 - val_mae: 1.1787
Epoch 8/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 55s 9s/step - loss: 1.9576 - mae: 1.9576 - val_loss: 0.6216 - val_mae: 0.6216
Epoch 9/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 54s 8s/step - loss: 1.8526 - mae: 1.8526 - val_loss: 0.5534 - val_mae: 0.5534
Epoch 10/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 54s 8s/step - loss: 1.7269 - mae: 1.7269 - val_loss: 0.6309 - val_mae: 0.6309
Epoch 11/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 55s 8s/step - loss: 1.6198 - mae: 1.6198 - val_loss: 0.6956 - val_mae: 0.6956
Epoch 12/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 55s 9s/step - loss: 1.4788 - mae: 1.4788 - val_loss: 1.3040 - val_mae: 1.3040
Epoch 13/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 55s 8s/step - loss: 1.3944 - mae: 1.3944 - val_loss: 1.0533 - val_mae: 1.0533
Epoch 14/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 54s 8s/step - loss: 1.2114 - mae: 1.2114 - val_loss: 1.1443 - val_mae: 1.1443
Epoch 15/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 56s 8s/step - loss: 1.1010 - mae: 1.1010 - val_loss: 1.1425 - val_mae: 1.1425
Epoch 16/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 54s 8s/step - loss: 0.9892 - mae: 0.9892 - val_loss: 1.0337 - val_mae: 1.0337
Epoch 17/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 55s 8s/step - loss: 0.8905 - mae: 0.8905 - val_loss: 0.7902 - val_mae: 0.7902
Epoch 18/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 52s 8s/step - loss: 0.7293 - mae: 0.7293 - val_loss: 0.6907 - val_mae: 0.6907
Epoch 19/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 83s 8s/step - loss: 0.6576 - mae: 0.6576 - val_loss: 0.6322 - val_mae: 0.6322
Epoch 20/20
7/7 ━━━━━━━━━━━━━━━━━━━━ 51s 8s/step - loss: 0.5339 - mae: 0.5339 - val_loss: 0.6769 - val_mae: 0.6769